New damsel career and Swap adjustments for blood kisses
TheOldRealms/TOR_Core_old pull request #33
Opened 2023-07-12 09:27 UTC by Z3rca

Damsel Adjustments and Career
-Changed Damsel "Powers of the Lady" to be battle prayers. Based on the Career, in case of warrior priest it will be sigmarite battle prayers, and as damsel these powers of the lady.
- added a new career for a damsel. The Damsel does not have an career ability. Yet a lot passives.
- The Damsel will start as a relatively classic mage, will however gain multiple lores during the playthrough. (Prophetesses are some sort devine, they can)

Career Benefits.
- new benefits, that are not unlocked via the rest of keystones or passives. The benefits will be unlocked upon reaching the different "Tier levels" of the career.
These Tier based logic will allow to unlock Attributes, or Abilities ect. That are usally permanent and will not be taken away beside career swaps.
- The Tiers can be implemented but dont have to.
- The benefits get triggered everytime the screen is opened, the programmer needs to ensure that the benefits that are added could not be added twice. For attributes, lores, ect. this is not a problem.
- the benefits are only given to Prophetesse, though it works similar for the vampire. 
- all Tiers can be defined via the CareerChoiceObject. Via the overriden "UnlockCareerBenefitsTier..."-Method 

Initial Career Setup and Blood kiss
- Career swaps, are rare, yet need to be made possible. One occasion for this is the blood kiss. The Player is stripped from all his career advantages and gets a new career assigned. Yet there might be varying restrictions, 
and intitial setups that need to be fullfilled once a new career is aquired. 

- The Intial Career Setups are configurated upon aquring a career.

-the initial setup will strip the player from undesired skills like faith, or in case of the blood knight from magic.

- fixed issues concerning blood kisses , like not beeing able to raise dead after combat or not able to interact with shrines when beeing blood kissed during gameplay.

2023-07-13 17:18 UTC, hunharibo requested changes

2023-07-13 17:18 UTC, hunharibo commented on CSharpSourceCode/CampaignMechanics/CustomDialogs/BloodKissCampaignBehavior.cs
> +            starter.AddDialogLine("bloodkiss_request_answer3", "bloodkiss_blooddragon_answer_line3", "bloodkiss_blooddragon_areyouready", "We do tolerate magic in our ranks, I will pacify you and str
I am guessing that would be "We do NOT tolerate magic"

2023-07-13 17:18 UTC, hunharibo commented on CSharpSourceCode/CharacterDevelopment/CareerSystem/Choices/BloodKnightCareerChoices.cs
> +            playerHero.HeroDeveloper.RemoveFocus(TORSkills.Faith,toRemoveFaith);
player will not get reimbursed for his removed points? just lose it without giving it back to the freely distributable pool?

2023-07-13 17:18 UTC, hunharibo commented on CSharpSourceCode/Extensions/HeroExtensions.cs
> +            hero.GetExtendedInfo().CurrentWindsOfMagic = result;
this will still attempt to run if info is null. Put it inside the nullcheck block. Dont't get the info twice, thats what the local variable is there for.

2023-07-13 17:18 UTC, hunharibo commented on CSharpSourceCode/Extensions/HeroExtensions.cs
> +        public static bool TryRemoveToRemoveKnownLore(this Hero hero, string lore)
Misspelled method name

2023-07-13 18:00 UTC, Z3rca commented on CSharpSourceCode/Extensions/HeroExtensions.cs
> +        public static bool TryRemoveToRemoveKnownLore(this Hero hero, string lore)
the method is not even used, sorry

2023-07-18 19:40 UTC, hunharibo approved these changes

2023-07-18 19:41 UTC, merged