Add canterian charger as horse to ink story fair with the horse market scene
TheOldRealms/TOR_Core_old pull request #60
Opened 2023-11-14 20:23 UTC by jzz111

- Changed persuasion check discount to 50% discount of 1000 gold
- Gave Canterian Charger for the purchase due to market value in traveling trader sell dialog

2023-11-14 20:59 UTC, hunharibo requested changes
Left some comments, nice first PR :)

2023-11-14 20:59 UTC, hunharibo commented on InkStories/Fair.ink
>      Your words work their magic, and the merchant agrees to lower the price by 25%. The merchant grumbles but respects your negotiating skills.
You probably want to adjust the 25% to 50% if the discount is changed :)

2023-11-14 20:59 UTC, hunharibo commented on InkStories/Fair.ink
> +~GiveItem("t2_empire_horse",1)
this will run regardless whether you have enough gold or you don't resulting in you potentially recieving a free horse if you don't have 2000 on you. This statement should be embedded in the conditional above. Same place as the GiveGold command.

2023-11-15 07:28 UTC, Z3rca approved these changes
all required changes have been adressed. approved.

2023-11-15 17:49 UTC, hunharibo approved these changes
Good changes, approved.

2023-11-15 21:43 UTC, merged