Necrarch and DE finalized
TheOldRealms/TOR_Core_old pull request #75
Opened 2024-03-24 00:12 UTC by Z3rca

2024-04-03 21:33 UTC, Z3rca commented on CSharpSourceCode/CharacterDevelopment/CareerSystem/CareerHelper.cs
> -                if(!passive.IsValidCharacterObject(characterObject)) continue;
line was doubled

2024-04-03 22:02 UTC, Z3rca commented on CSharpSourceCode/Models/TORPartySpeedCalculatingModel.cs
Another debuff. Not having any dark energy and a very high unbalance result in losing a lot movement speed.

2024-04-04 16:47 UTC, hunharibo requested changes

2024-04-04 16:47 UTC, hunharibo commented on CSharpSourceCode/AbilitySystem/Scripts/VortexScript.cs
> +            oldFrame.origin.z = heightAtPosition + Ability.Template.Offset;
Is there a particular reason for this? To be fair I don't remember why we did division by 2, but why the change?

2024-04-04 16:47 UTC, hunharibo commented on CSharpSourceCode/BattleMechanics/CareerPerkMissionBehavior.cs
> +        private float currentSecondTick;
naming violation, please start with underscore. Also a better name, maybe currentTime?

2024-04-04 16:47 UTC, hunharibo commented on CSharpSourceCode/BattleMechanics/CareerPerkMissionBehavior.cs
> +            if (currentSecondTick > 1)
add private variable for frequency instead of hardcoding it to 1

2024-04-04 16:47 UTC, hunharibo commented on CSharpSourceCode/BattleMechanics/CareerPerkMissionBehavior.cs
> +                if (!affectorAgent.HasMount&&!affectorAgent.WieldedOffhandWeapon.IsEmpty&&affectorAgent.WieldedOffhandWeapon.Item!=null&&affectorAgent.WieldedOffhandWeapon.Item.IsMagicalStaff()&& cho
fix formatting pls, this is unreadable

2024-04-04 16:47 UTC, hunharibo commented on CSharpSourceCode/CampaignMechanics/SpellTrainers/SpellTrainerInTownBehavior.cs
> +                            continue;
Is it intended that disabled cultures check is not running for necrarchs? I think perhaps this could be done cleaner.

2024-04-04 16:47 UTC, hunharibo commented on CSharpSourceCode/CampaignMechanics/TORCustomSettlement/TORCustomSettlementCampaignBehavior.cs
> +        private Dictionary<string, int> leveledUpUndead = new Dictionary<string, int>();
naming violation, please lead with underscore

2024-04-04 16:47 UTC, hunharibo commented on CSharpSourceCode/CampaignMechanics/TORCustomSettlement/TORCustomSettlementCampaignBehavior.cs
> +            var component = settlement.SettlementComponent as ShrineComponent;
component may be null here. Not ever component is of type ShrineComponent.

2024-04-04 16:47 UTC, hunharibo commented on CSharpSourceCode/CampaignMechanics/TORCustomSettlement/TORCustomSettlementCampaignBehavior.cs
> +                    var component = settlement.SettlementComponent as ShrineComponent;
why are these 2 lines needed? the block scoped variables are not used anywhere

2024-04-04 16:47 UTC, hunharibo commented on CSharpSourceCode/Extensions/ExtendedInfoSystem/HeroExtendedInfo.cs
> +                            }
why not do this as part of the careerhelper method? Ideally this should be in a model class

2024-04-04 18:21 UTC, Z3rca commented on CSharpSourceCode/AbilitySystem/Scripts/VortexScript.cs
> +            oldFrame.origin.z = heightAtPosition + Ability.Template.Offset;
what was the offset used for? The Problem was, that some spells need to be shifted a bit up and down depending on the visuals. Especially in the case of the dogs the radius /2 calculation was not suiting. so far we only had spells like the fire storm or the black horror, which fit this calculation, so we never noticed

2024-04-04 19:46 UTC, Z3rca commented on CSharpSourceCode/CampaignMechanics/SpellTrainers/SpellTrainerInTownBehavior.cs
> +                            continue;
yes this is intentional and very specific, i moved it out of the method yet, I don't see how we can solve this cleaner.

2024-04-05 15:50 UTC, hunharibo approved these changes

2024-04-05 17:01 UTC, merged